### ISSUE TITLE
Fix method name typo

### ISSUE THREAD

**Issue by hakash** [hakash/nanoqueue#6]
This issue is one that is perfect for new contributors. All you need to do is fix a small typo in a method name in the main module, that through code-completion in my IDE has made it's way unnoticed into the example modules as well.

The method in `nanoqueue.js` is `regsiterModule` which obviously should be named `registerModule`. 

All the relevant module files are in the `modules/` subfolder, and the `nanoqueue.js` main module is located at the root folder.

Good luck!

**Comment by jeanha124** [comment]
can I do this?

**Comment by latonis** [comment]
Just updated all the method calls and the original method name :)

**Comment by hakash** [comment]
@Latonis I never expected to get help this fast :) Thank you for doing this. It was, to be honest, more an exercise to test getting help, and also helping someone getting a t-shirt 😄 

@jeanha124 I'm sorry, Latonis beat you to it. He had his first PR in before your comment. I might find something else to share, and if I do, I'll post an issue with the same labels so you can see them.

**Comment by latonis** [comment]
@hakash Thanks for giving an opportunity to fix things! 😄 Those were my first PRs to others' code ❗️ Glad to be able to help 👍

**Comment by hakash** [comment]
@Latonis I haven't been able to make an npm package of the project yet, but feel free to use and experiment with the framework anyways. If you even need components on your page or modules in your server code, to interact without hard coding them to each other, just design a common information schema, decide what topics to use and start sending messages. 

It's a great way to spread the same info to multiple modules/components/recipients with one simple push.

**Comment by hakash** [comment]
@Latonis Oh, and I would recommend that you do at least another 4 PRs with some more meat to them, as the issue I posted was really only one small PR. 😉
